#!/bin/sh

#  COPYRIGHT LICENSE: This information contains sample code provided in source 
#  code form. You may copy, modify, and distribute these sample programs in any
#  form without payment to IBM for the purposes of developing, using, marketing
#  or distributing application programs conforming to the application programming
#  interface for the operating platform for which the sample code is written. 
#  Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE
#  ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
#  INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF
#  MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE,
#  AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR
#  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT
#  OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION TO
#  PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO THE
#  SAMPLE SOURCE CODE.

SAMPLES_HOME=$(dirname $(readlink -f $0))/..

ANTCLASSPATH="$JAVA_HOME/lib/tools.jar:$WAS_HOME/lib/j2ee.jar:$WAS_HOME/plugins/com.ibm.ws.runtime.jar:$WAS_HOME/plugins/com.ibm.ws.runtime.dist.jar:$WAS_HOME/plugins/com.ibm.ws.emf.jar:$WAS_HOME/plugins/com.ibm.ws.wccm.jar:$WAS_HOME/lib/bootstrap.jar:$WAS_HOME/plugins/com.ibm.ws.bootstrap.jar:$WAS_HOME/plugins/org.eclipse.core.runtime_.jar:$WAS_HOME/plugins/org.eclipse.emf.commonj.sdo.jar:$WAS_HOME/plugins/org.eclipse.emf.ecore.jar:$WAS_HOME/plugins/org.eclipse.emf.common.jar:$WAS_HOME/plugins/org.eclipse.emf.ecore.sdo.jar:$WAS_HOME/plugins/com.ibm.ws.sib.webservices.jar:$WAS_HOME/plugins/com.ibm.ws.webcontainer.jar:$WAS_HOME/plugins/javax.j2ee.jsf.jar:$CLASSPATH"

export ANTCLASSPATH

"$JAVA_HOME/jre/bin/java" $WAS_LOGGING -classpath $ANTCLASSPATH org.apache.tools.ant.Main -Dbasedir="$SAMPLES_HOME" -Dwas_home="$WAS_HOME" $@
